Msi
mskcc/roslin-variants pull request #185
Opened 2018-05-10 15:43 UTC by timosong

Added msisensor to the variant caller module and made appropriate changes. 
This should also generate a new directory called "analysis" for future output. 

i hope this works

2018-05-10 17:34 UTC, allanbolipata commented
add to whitelist

2018-05-10 19:34 UTC, timosong commented
test this, please

2018-05-11 14:07 UTC, nikhil commented on setup/bin/roslin_portal_helper.py
> +			print row
Seems like an artifact, please remove the print statement.

2018-05-11 14:12 UTC, nikhil commented on setup/cwl/project-workflow-sv.cwl
> +- file:///ifs/work/pi/roslin-test/targeted-variants/200/roslin-core/2.0.0/schemas/dcterms.rdf
Just to be consistent with the rest of our cwls can you revert the schemas to:

- http://dublincore.org/2012/06/14/dcterms.rdf
- http://xmlns.com/foaf/spec/20140114.rdf
- http://usefulinc.com/ns/doap#

2018-05-11 14:12 UTC, nikhil commented on setup/cwl/project-workflow-sv.cwl
> +<<<<<<< HEAD
This segment should be removed

2018-05-11 14:14 UTC, nikhil commented on setup/cwl/project-workflow.cwl
> +- file:///ifs/work/pi/roslin-test/targeted-variants/200/roslin-core/2.0.0/schemas/dcterms.rdf
Same as workflow-sv
Just to be consistent with the rest of our cwls can you revert the schemas to:

- http://dublincore.org/2012/06/14/dcterms.rdf
- http://xmlns.com/foaf/spec/20140114.rdf
- http://usefulinc.com/ns/doap#

2018-05-11 14:21 UTC, nikhil requested changes
Left a few comments.

2018-05-11 15:39 UTC, timosong commented on setup/bin/roslin_portal_helper.py
> +	job_done = True
I don't remember making this change.. Changing it back to `job_done = False`

2018-05-11 15:45 UTC, timosong commented
test this, please

2018-05-11 18:00 UTC, timosong commented
test this, please

2018-05-14 15:52 UTC, timosong commented
test this, please

2018-05-14 18:08 UTC, timosong commented
test this, please

2018-05-14 20:49 UTC, nikhil approved these changes

2018-12-26 17:58 UTC, ckandoth commented
With all the CWL changes in `2.5.0`, it will be easier to create a new branch, rather than try to merge this one. I'll close this PR, but the code will remain in the `msi` branch, till we can work it into a `2.5.*` release

2018-12-26 17:58 UTC, closed without merging